{"uuid": "01ddd243-35b1-4a5a-af4a-97d56c62700c", "children": ["a0e9bafc-17f2-408f-8077-541209dcf321", "55123f27-b5a3-4b9b-8e59-af6ffdb321f1"], "befores": [{"name": "driver", "status": "passed", "start": 1720079358664, "stop": 1720079363818}], "afters": [{"name": "driver::0", "status": "broken", "statusDetails": {"message": "KeyboardInterrupt\n", "trace": "  File \"C:\\Users\\FAZIL\\PycharmProjects\\API_Testing_Practise\\pythonProject\\.venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\FAZIL\\PycharmProjects\\API_Testing_Practise\\pythonProject\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 896, in _teardown_yield_fixture\n    next(it)\n  File \"C:\\Users\\FAZIL\\Desktop\\Discover-Automation\\DiscoverAutomation\\testcases\\conftest.py\", line 16, in driver\n    driver.quit()\n  File \"C:\\Users\\FAZIL\\PycharmProjects\\API_Testing_Practise\\pythonProject\\.venv\\Lib\\site-packages\\selenium\\webdriver\\chromium\\webdriver.py\", line 193, in quit\n    self.service.stop()\n  File \"C:\\Users\\FAZIL\\PycharmProjects\\API_Testing_Practise\\pythonProject\\.venv\\Lib\\site-packages\\selenium\\webdriver\\common\\service.py\", line 146, in stop\n    self.send_remote_shutdown_command()\n  File \"C:\\Users\\FAZIL\\PycharmProjects\\API_Testing_Practise\\pythonProject\\.venv\\Lib\\site-packages\\selenium\\webdriver\\common\\service.py\", line 126, in send_remote_shutdown_command\n    request.urlopen(f\"{self.service_url}/shutdown\")\n  File \"C:\\Program Files\\Python311\\Lib\\urllib\\request.py\", line 216, in urlopen\n    return opener.open(url, data, timeout)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\urllib\\request.py\", line 519, in open\n    response = self._open(req, data)\n               ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\urllib\\request.py\", line 536, in _open\n    result = self._call_chain(self.handle_open, protocol, protocol +\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\urllib\\request.py\", line 496, in _call_chain\n    result = func(*args)\n             ^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\urllib\\request.py\", line 1377, in http_open\n    return self.do_open(http.client.HTTPConnection, req)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\urllib\\request.py\", line 1348, in do_open\n    h.request(req.get_method(), req.selector, req.data, headers,\n  File \"C:\\Program Files\\Python311\\Lib\\http\\client.py\", line 1298, in request\n    self._send_request(method, url, body, headers, encode_chunked)\n  File \"C:\\Program Files\\Python311\\Lib\\http\\client.py\", line 1344, in _send_request\n    self.endheaders(body, encode_chunked=encode_chunked)\n  File \"C:\\Program Files\\Python311\\Lib\\http\\client.py\", line 1293, in endheaders\n    self._send_output(message_body, encode_chunked=encode_chunked)\n  File \"C:\\Program Files\\Python311\\Lib\\http\\client.py\", line 1052, in _send_output\n    self.send(msg)\n  File \"C:\\Program Files\\Python311\\Lib\\http\\client.py\", line 990, in send\n    self.connect()\n  File \"C:\\Program Files\\Python311\\Lib\\http\\client.py\", line 956, in connect\n    self.sock = self._create_connection(\n                ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\socket.py\", line 843, in create_connection\n    exceptions.clear()  # raise only the last error\n    ^^^^^^^^^^^^^^^^^^\n"}, "start": 1720079441382, "stop": 1720079445488}], "start": 1720079358664, "stop": 1720079445488}